<?php

namespace DoctrineProxies\__CG__\App\Models\Locations;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Country extends \App\Models\Locations\Country implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'name', 'iso2', 'iso3', 'isoNumeric', 'fipsCode', 'capital', 'isEU', 'isUK', 'isUSTerritory', 'continent', 'subdivisions', 'postalDistricts'];
        }

        return ['__isInitialized__', 'id', 'name', 'iso2', 'iso3', 'isoNumeric', 'fipsCode', 'capital', 'isEU', 'isUK', 'isUSTerritory', 'continent', 'subdivisions', 'postalDistricts'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Country $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getIso2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIso2', []);

        return parent::getIso2();
    }

    /**
     * {@inheritDoc}
     */
    public function getIso3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIso3', []);

        return parent::getIso3();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsoNumeric()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsoNumeric', []);

        return parent::getIsoNumeric();
    }

    /**
     * {@inheritDoc}
     */
    public function getFipsCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFipsCode', []);

        return parent::getFipsCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getCapital()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapital', []);

        return parent::getCapital();
    }

    /**
     * {@inheritDoc}
     */
    public function isEU()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEU', []);

        return parent::isEU();
    }

    /**
     * {@inheritDoc}
     */
    public function isUK()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUK', []);

        return parent::isUK();
    }

    /**
     * {@inheritDoc}
     */
    public function isUSTerritory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUSTerritory', []);

        return parent::isUSTerritory();
    }

    /**
     * {@inheritDoc}
     */
    public function getContinent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContinent', []);

        return parent::getContinent();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubdivisions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubdivisions', []);

        return parent::getSubdivisions();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalDistricts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalDistricts', []);

        return parent::getPostalDistricts();
    }

}
